### 
GET http://localhost:3000/api/v1/arrays HTTP/1.1


### POST Content-Type: application/json;

GET http://localhost:3000/api/v1/lesson/3 HTTP/1.1

###
GET http://localhost:3000/api/v1/lesson/2019/batman HTTP/1.1
###
GET http://localhost:3000/api/v1/lesson/2019/batman?sortBy=name HTTP/1.1

###
GET http://localhost:3000/api/v1/lesson HTTP/1.1


###
POST http://localhost:3000/api/v1/lessons HTTP/1.1
Content-Type: application/json;

{

    "lesson":"lesson 5"
}

###
PUT http://localhost:3000/api/v1/lesson/1 HTTP/1.1
Content-Type: application/json;

{

    "lesson":"lesson 5"
}

###
DELETE  http://localhost:3000/api/v1/lesson/1 HTTP/1.1


